"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const jsx_runtime_1 = require("react/jsx-runtime");
const { Panel, PanelGroup, PanelResizeHandle } = require('react-resizable-panels');
const PromptGenerator = require('./components/PromptGenerator').default;
const ImageEditor = require('./components/ImageEditor').default;
const AICommentator = require('./components/AICommentator').default;
function App() {
    return ((0, jsx_runtime_1.jsxs)("div", { className: "h-screen bg-slate-900 text-slate-100 flex flex-col", children: [(0, jsx_runtime_1.jsx)("header", { className: "bg-slate-800 border-b border-slate-700 px-6 py-4", children: (0, jsx_runtime_1.jsxs)("div", { className: "flex items-center justify-between", children: [(0, jsx_runtime_1.jsx)("h1", { className: "text-2xl font-bold text-primary-400", children: "AIDesktop Image Suite" }), (0, jsx_runtime_1.jsxs)("div", { className: "flex items-center space-x-4", children: [(0, jsx_runtime_1.jsx)("span", { className: "text-sm text-slate-400", children: "v0.1.0" }), (0, jsx_runtime_1.jsx)("button", { className: "btn-secondary text-sm", children: "Settings" })] })] }) }), (0, jsx_runtime_1.jsx)("main", { className: "flex-1 overflow-hidden", children: (0, jsx_runtime_1.jsxs)(PanelGroup, { direction: "horizontal", className: "h-full", children: [(0, jsx_runtime_1.jsx)(Panel, { defaultSize: 25, minSize: 20, maxSize: 35, children: (0, jsx_runtime_1.jsx)("div", { className: "h-full bg-slate-800 border-r border-slate-700", children: (0, jsx_runtime_1.jsx)(PromptGenerator, {}) }) }), (0, jsx_runtime_1.jsx)(PanelResizeHandle, { className: "w-1 bg-slate-700 hover:bg-primary-500 transition-colors" }), (0, jsx_runtime_1.jsx)(Panel, { defaultSize: 50, minSize: 30, maxSize: 60, children: (0, jsx_runtime_1.jsx)("div", { className: "h-full bg-slate-800", children: (0, jsx_runtime_1.jsx)(ImageEditor, {}) }) }), (0, jsx_runtime_1.jsx)(PanelResizeHandle, { className: "w-1 bg-slate-700 hover:bg-primary-500 transition-colors" }), (0, jsx_runtime_1.jsx)(Panel, { defaultSize: 25, minSize: 20, maxSize: 35, children: (0, jsx_runtime_1.jsx)("div", { className: "h-full bg-slate-800 border-l border-slate-700", children: (0, jsx_runtime_1.jsx)(AICommentator, {}) }) })] }) }), (0, jsx_runtime_1.jsx)("footer", { className: "bg-slate-800 border-t border-slate-700 px-6 py-2", children: (0, jsx_runtime_1.jsxs)("div", { className: "flex items-center justify-between text-sm text-slate-400", children: [(0, jsx_runtime_1.jsx)("span", { children: "Ready for AI-powered image editing" }), (0, jsx_runtime_1.jsxs)("div", { className: "flex items-center space-x-4", children: [(0, jsx_runtime_1.jsxs)("span", { children: ["HF API: ", (0, jsx_runtime_1.jsx)("span", { className: "text-green-400", children: "\u2713 Configured" })] }), (0, jsx_runtime_1.jsxs)("span", { children: ["Supabase: ", (0, jsx_runtime_1.jsx)("span", { className: "text-yellow-400", children: "Configure .env" })] })] })] }) })] }));
}
module.exports = { default: App };
